on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ vars.DOCKER_PASSWORD }}
  CONTAINER_NAME: todolist
  BE_IMAGE_NAME: todolist_backend
  FE_IMAGE_NAME: todolist_frontend
permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: build docker image
      run: |
        export COMMIT_SHA_SHORT=`echo ${GITHUB_SHA} | cut -c1-7`
        echo $COMMIT_SHA_SHORT
        docker build -t $DOCKER_USERNAME/$BE_IMAGE_NAME:$COMMIT_SHA_SHORT -f client/Dockerfile client
        docker build -t $DOCKER_USERNAME/$FE_IMAGE_NAME:$COMMIT_SHA_SHORT  -f server/Dockerfile server

  push-image:
    runs-on: self-hosted
    needs: build
    steps:
    - name: push docker image
      run: |
        export COMMIT_SHA_SHORT=`echo ${GITHUB_SHA} | cut -c1-7`
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push $DOCKER_USERNAME/$BE_IMAGE_NAME:$COMMIT_SHA_SHORT
        docker push $DOCKER_USERNAME/$FE_IMAGE_NAME:$COMMIT_SHA_SHORT
        

  deploy:
    permissions:
      contents: none
    runs-on: self-hosted
    needs: push-image

    steps:
    - name: run docker image
      run: |
        export COMMIT_SHA_SHORT=`echo ${GITHUB_SHA} | cut -c1-7`
        docker compose up -d
        
        
